### ISSUE TITLE
Nicht alle Daten werden gelöscht

### ISSUE THREAD

**Issue by RogerSik** [RogerSik/OpenVZ-Template-Creator#1]
Erstellt man paar Textdateien in das gewünschte Verzeichnis wo die Distribution installiert werden soll so löscht 1_create_system.sh beim ausführen sie gar nicht.

**Comment by RogerSik** [comment]
Ich kann mir nur den Fehler erklären das durch die ganzen if und else Abfrage irgendwas schief geht. 

Ein manuelles rm -rf $input_path/\* funktioniert.

**Comment by v1tzl1** [comment]
Autsch http://github.com/v1tzl1/OpenVZ-Template-Creator/commit/271aac5468bd9bb4c4290a746e7088640abed4f9
;)

**Comment by v1tzl1** [comment]
Ähm da ist noch mehr kaputt, moment

**Comment by RogerSik** [comment]
Hast du den Fix mal ausprobiert bevor du ihn hochgeladen hast?
Ich krieg nämlich ein Syntax Error.

Edit1: Ah hast du ja selber bemerkt. Darum ja ausprobieren bevor man was commitet/hochladet. ;P

**Comment by v1tzl1** [comment]
Jo das fi war nicht das Problem das war nur falsch eingerückt und ich dachte da wär der Fehler und wollte den schnell fixen ohne mich damit auseinander zu setzen, sorry :(
So sollte es gehen (zumindest bei mir) http://github.com/v1tzl1/OpenVZ-Template-Creator/commit/cd0cb903c7ea5524b028b3cc6c00a28fbfb876a3

**Comment by RogerSik** [comment]
Der Code funktioniert bei mir auch und hab ihn jetzt mal integriert. Aber nächstesmal lasse bitte die echo Befehle aus, weil man sie nicht sehen wird denn es wird ja sofort zum nächsten dialog Befehl gewechselt.
